version: "3.8"
services:
  hugo:
    build:
      context: ./hugo
      dockerfile: Dockerfile
    volumes:
      - $PWD/test-src/:/src
      - $PWD/site/:/site
    environment:
      # change these variables to update the site's theme and/or baseURL
      - HUGO_THEME=sk2
      - HUGO_BASEURL=https://example.org
    restart: always
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/caddy/caddyfile/:/etc/caddy/
      - $PWD/site:/srv
      - $PWD/caddy/caddy-data:/data
      - $PWD/caddy/caddy-config:/config
    restart: unless-stopped